from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    """跨 API、Worker 和模型适配器共享的稳定错误码。"""

    WORKSPACE_PATH_ESCAPE = "WORKSPACE_PATH_ESCAPE"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
    VIDEO_FFMPEG_UNAVAILABLE = "VIDEO_FFMPEG_UNAVAILABLE"
    VIDEO_FFPROBE_UNAVAILABLE = "VIDEO_FFPROBE_UNAVAILABLE"
    VIDEO_BINARY_PROBE_FAILED = "VIDEO_BINARY_PROBE_FAILED"
    VIDEO_PROCESS_TIMEOUT = "VIDEO_PROCESS_TIMEOUT"
    VIDEO_PROCESS_CANCELLED = "VIDEO_PROCESS_CANCELLED"
    VIDEO_PROCESS_OUTPUT_TOO_LARGE = "VIDEO_PROCESS_OUTPUT_TOO_LARGE"
    VIDEO_PROCESS_FAILED = "VIDEO_PROCESS_FAILED"
    VIDEO_PROBE_INVALID = "VIDEO_PROBE_INVALID"
    VIDEO_STREAM_MISSING = "VIDEO_STREAM_MISSING"
    VIDEO_STREAM_COUNT_EXCEEDED = "VIDEO_STREAM_COUNT_EXCEEDED"
    VIDEO_DURATION_LIMIT_EXCEEDED = "VIDEO_DURATION_LIMIT_EXCEEDED"
    VIDEO_RESOLUTION_LIMIT_EXCEEDED = "VIDEO_RESOLUTION_LIMIT_EXCEEDED"
    VIDEO_FRAME_RATE_LIMIT_EXCEEDED = "VIDEO_FRAME_RATE_LIMIT_EXCEEDED"
    VIDEO_DISK_SPACE_INSUFFICIENT = "VIDEO_DISK_SPACE_INSUFFICIENT"
    VIDEO_INPUT_INVALID = "VIDEO_INPUT_INVALID"
    VIDEO_OUTPUT_INVALID = "VIDEO_OUTPUT_INVALID"
    VIDEO_OUTPUT_TOO_LARGE = "VIDEO_OUTPUT_TOO_LARGE"
    VISUAL_DEPENDENCY_UNAVAILABLE = "VISUAL_DEPENDENCY_UNAVAILABLE"
    VISUAL_MEDIA_INVALID = "VISUAL_MEDIA_INVALID"
    VISUAL_RESULT_INVALID = "VISUAL_RESULT_INVALID"
    SPEECH_DEPENDENCY_UNAVAILABLE = "SPEECH_DEPENDENCY_UNAVAILABLE"
    SPEECH_MODEL_UNAVAILABLE = "SPEECH_MODEL_UNAVAILABLE"
    SPEECH_AUTHENTICATION_FAILED = "SPEECH_AUTHENTICATION_FAILED"
    SPEECH_AUDIO_INVALID = "SPEECH_AUDIO_INVALID"
    SPEECH_SUBPROCESS_TIMEOUT = "SPEECH_SUBPROCESS_TIMEOUT"
    SPEECH_SUBPROCESS_CRASHED = "SPEECH_SUBPROCESS_CRASHED"
    SPEECH_SUBPROCESS_RESPONSE_INVALID = "SPEECH_SUBPROCESS_RESPONSE_INVALID"
    BAIDU_API_KEY_UNAVAILABLE = "BAIDU_API_KEY_UNAVAILABLE"
    BAIDU_SECRET_KEY_UNAVAILABLE = "BAIDU_SECRET_KEY_UNAVAILABLE"
    QWEN_ENDPOINT_UNAVAILABLE = "QWEN_ENDPOINT_UNAVAILABLE"
    QWEN_API_KEY_UNAVAILABLE = "QWEN_API_KEY_UNAVAILABLE"
    QWEN_MODEL_ID_UNAVAILABLE = "QWEN_MODEL_ID_UNAVAILABLE"
    OSS_CONFIGURATION_INVALID = "OSS_CONFIGURATION_INVALID"
    OSS_AUTHENTICATION_FAILED = "OSS_AUTHENTICATION_FAILED"
    OSS_OBJECT_INVALID = "OSS_OBJECT_INVALID"
    SILERO_DEPENDENCY_UNAVAILABLE = "SILERO_DEPENDENCY_UNAVAILABLE"
    SILERO_MODEL_UNAVAILABLE = "SILERO_MODEL_UNAVAILABLE"
    LIVE_AUTHORIZED_AUDIO_UNAVAILABLE = "LIVE_AUTHORIZED_AUDIO_UNAVAILABLE"
    LIVE_AUTHORIZED_KEYFRAME_UNAVAILABLE = "LIVE_AUTHORIZED_KEYFRAME_UNAVAILABLE"
    LIVE_AUTHORIZED_CLIP_UNAVAILABLE = "LIVE_AUTHORIZED_CLIP_UNAVAILABLE"
    LIVE_FIVE_LANGUAGE_AUDIO_UNAVAILABLE = "LIVE_FIVE_LANGUAGE_AUDIO_UNAVAILABLE"
    OCR_LANGUAGE_UNSUPPORTED = "OCR_LANGUAGE_UNSUPPORTED"
    OCR_AUTHENTICATION_FAILED = "OCR_AUTHENTICATION_FAILED"
    OCR_RESPONSE_INVALID = "OCR_RESPONSE_INVALID"
    QWEN_CAPABILITY_UNAVAILABLE = "QWEN_CAPABILITY_UNAVAILABLE"
    QWEN_AUTHENTICATION_FAILED = "QWEN_AUTHENTICATION_FAILED"
    QWEN_REQUEST_REJECTED = "QWEN_REQUEST_REJECTED"
    QWEN_RESPONSE_INVALID = "QWEN_RESPONSE_INVALID"
    INVALID_EVIDENCE_CURSOR = "INVALID_EVIDENCE_CURSOR"
    KEYFRAME_NOT_FOUND = "KEYFRAME_NOT_FOUND"
    INVALID_PATH_COMPONENT = "INVALID_PATH_COMPONENT"
    INVALID_VIDEO_FILENAME = "INVALID_VIDEO_FILENAME"
    VIDEO_FORMAT_UNSUPPORTED = "VIDEO_FORMAT_UNSUPPORTED"
    VIDEO_MIME_MISMATCH = "VIDEO_MIME_MISMATCH"
    VIDEO_FILE_TOO_LARGE = "VIDEO_FILE_TOO_LARGE"
    VIDEO_FILE_EMPTY = "VIDEO_FILE_EMPTY"
    VIDEO_OBJECT_NOT_FOUND = "VIDEO_OBJECT_NOT_FOUND"
    VIDEO_DIGEST_MISMATCH = "VIDEO_DIGEST_MISMATCH"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    ARTIFACT_SCHEMA_INVALID = "ARTIFACT_SCHEMA_INVALID"
    ARTIFACT_UPSTREAM_MISMATCH = "ARTIFACT_UPSTREAM_MISMATCH"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_LEASE_LOST = "JOB_LEASE_LOST"
    JOB_CANCELLED = "JOB_CANCELLED"
    DEPENDENCY_TEMPORARY_FAILURE = "DEPENDENCY_TEMPORARY_FAILURE"
    SYSTEM_FAILURE = "SYSTEM_FAILURE"
    OUT_OF_MEMORY = "OUT_OF_MEMORY"
    VIDEO_RUN_NOT_FOUND = "VIDEO_RUN_NOT_FOUND"
    VIDEO_RESULT_NOT_READY = "VIDEO_RESULT_NOT_READY"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    JOB_NOT_RETRYABLE = "JOB_NOT_RETRYABLE"
    DUPLICATE_EVIDENCE_ID = "DUPLICATE_EVIDENCE_ID"
    UNKNOWN_EVIDENCE_REFERENCE = "UNKNOWN_EVIDENCE_REFERENCE"
    EVIDENCE_TYPE_MISMATCH = "EVIDENCE_TYPE_MISMATCH"
    UNKNOWN_CHAPTER_REFERENCE = "UNKNOWN_CHAPTER_REFERENCE"
    EVIDENCE_OUTSIDE_CHAPTER = "EVIDENCE_OUTSIDE_CHAPTER"
    EVIDENCE_RELATION_INVALID = "EVIDENCE_RELATION_INVALID"
    INPUT_BUDGET_EXCEEDED = "INPUT_BUDGET_EXCEEDED"
    RESULT_SCHEMA_UNSUPPORTED = "RESULT_SCHEMA_UNSUPPORTED"
    TEXT_LLM_AUTHENTICATION_FAILED = "TEXT_LLM_AUTHENTICATION_FAILED"
    TEXT_LLM_CAPABILITY_UNAVAILABLE = "TEXT_LLM_CAPABILITY_UNAVAILABLE"
    TEXT_LLM_RESPONSE_INVALID = "TEXT_LLM_RESPONSE_INVALID"
    EVIDENCE_OUTSIDE_SEGMENT = "EVIDENCE_OUTSIDE_SEGMENT"
    DUPLICATE_SEGMENT_ID = "DUPLICATE_SEGMENT_ID"
    UNKNOWN_SEGMENT_REFERENCE = "UNKNOWN_SEGMENT_REFERENCE"
    EVALUATION_DATASET_INVALID = "EVALUATION_DATASET_INVALID"
    EVALUATION_ARTIFACT_INVALID = "EVALUATION_ARTIFACT_INVALID"
    M1_SAMPLE_COUNT_INVALID = "M1_SAMPLE_COUNT_INVALID"
    M1_DURATION_TOO_SHORT = "M1_DURATION_TOO_SHORT"
    M1_RESOLUTION_TOO_SMALL = "M1_RESOLUTION_TOO_SMALL"
    M1_AUTHORIZATION_UNAVAILABLE = "M1_AUTHORIZATION_UNAVAILABLE"
    M1_MEDIA_INVALID = "M1_MEDIA_INVALID"
    M1_PROBE_MISMATCH = "M1_PROBE_MISMATCH"
    M1_PSUTIL_UNAVAILABLE = "M1_PSUTIL_UNAVAILABLE"
    M1_RUNTIME_UNAVAILABLE = "M1_RUNTIME_UNAVAILABLE"


class VideoDemoError(Exception):
    """包含稳定错误码、但不泄漏第三方实现细节的领域异常。"""

    def __init__(
        self,
        code: ErrorCode,
        message: str,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}


_RETRYABLE_ERROR_CODES = frozenset(
    {
        ErrorCode.DEPENDENCY_TEMPORARY_FAILURE,
        ErrorCode.SPEECH_SUBPROCESS_TIMEOUT,
        ErrorCode.SPEECH_SUBPROCESS_CRASHED,
    }
)


def is_retryable_error_code(code: ErrorCode) -> bool:
    return code in _RETRYABLE_ERROR_CODES
